# Generated by Django 2.0.5 on 2018-06-01 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_auto_20180601_1204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemimage',
            name='item',
        ),
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='items.ItemImage'),
        ),
    ]
