# Generated by Django 2.0.5 on 2018-06-01 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_auto_20180601_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemimage',
            name='image_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='items.Category'),
        ),
    ]
