# Generated by Django 2.0.5 on 2018-06-01 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_itemimage_image_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemimage',
            name='image',
            field=models.ImageField(upload_to='static/media/'),
        ),
    ]
