# Generated by Django 2.0.5 on 2018-06-03 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_auto_20180601_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemimage',
            name='image',
            field=models.ImageField(upload_to='items_images/'),
        ),
    ]
