# Generated by Django 2.0.5 on 2018-06-03 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_auto_20180603_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='items.ItemImage'),
        ),
    ]
