# Generated by Django 2.0.5 on 2018-06-03 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0008_auto_20180603_1314'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='image',
            new_name='item_image',
        ),
    ]
